### ISSUE TITLE
[BUG] Liveries missing from manager

### ISSUE THREAD

**Issue by NNowakowski** [MSFS-Mega-Pack/MSFS2020-livery-manager#125]
## Description

Some liveries seem to be missing from the manager, in this case I've noticed the Longitude not being listed at all

## To reproduce

1. Click available liveries
2. Search for the Citation Longitude

## Environment

**Manager version:** 0.2.2

**FS2020 Version:** Latest

## Screenshots or videos

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/16933892/97084388-e874ea80-1616-11eb-879a-3e3c3c57caed.png)

</details>

**Comment by davwheat** [comment]
Hey @GewoonJaap handles the backend, so I've assigned him to this issue.

**Comment by GewoonJaap** [comment]
Looks like the files are also not on the CDN, does the Longitude actually have liveries in the megapack?

**Comment by GewoonJaap** [comment]
https://github.com/MSFS-Mega-Pack/MSFS2020-Livery-API/blob/master/livery-store/sync-files.js 
Longitude is not in the prefix list, that is why it is no here. Will fix ASAP

**Comment by NNowakowski** [comment]
It does indeed have a few liveries
![image](https://user-images.githubusercontent.com/16933892/97092485-8fbc4680-1644-11eb-9869-cc7128a692cc.png)

**Comment by GewoonJaap** [comment]
Yup thanks! Will add it to the prefix

**Comment by GewoonJaap** [comment]
https://github.com/MSFS-Mega-Pack/MSFS2020-Livery-API/commit/f6c79f6217c56e479e56d7dd98f88d11b6b069d2 Fixed!

**Comment by GewoonJaap** [comment]
It might take a while for it to be added

**Comment by davwheat** [comment]
Closing, as it should be fixed now! Thanks @GewoonJaap :P

**Comment by GewoonJaap** [comment]
Files are being upload, should appear soon!

**Comment by NNowakowski** [comment]
Thanks! I've went ahead and checked for more missing aircrafts on that file and created an according PR https://github.com/MSFS-Mega-Pack/MSFS2020-Livery-API/pull/8
