### ISSUE TITLE
[FEAT] Detection of already manually installed liveries

### ISSUE THREAD

**Issue by NNowakowski** [MSFS-Mega-Pack/MSFS2020-livery-manager#127]
## Description

To ease the process of migrating users to the manager, it would be nice to have a functionality to automatically detect manually installed liveries belonging to the MegaPack. This way no re-download would be required, especially since there is no function to download **all** liveries at once, without having to click through each airplane and clicking "select all".

## Solution

Give the user the option to have the manager search through the specified community folder for already installed MegaPack liveries. This could be done during initial start, after the user entered his community folder, or be a seperate function in one of the tabs so one could re-use it after having installed more liveries manually.

### Why is this the best solution?

Ease of migration between manual and automatic installation, making it more attractive for the user.

**Comment by davwheat** [comment]
We can't really do this. There are far too many factors which could result in detection errors.

**Comment by NNowakowski** [comment]
Already thought something like that would be the reason why you guys didn't include a feature like it. I guess there is no way currently to figure out if a livery belongs to the megapack or if it was downloaded from somewhere else.

**Comment by davwheat** [comment]
Yeah, we thought about it, but couldn't think of.a good way other than zipping up the folder and comparing hashes.

If the liveries had proper manifests, we could have used them, but creators tend not to set up their manifests properly.
