### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by in-04** [MSFS-Mega-Pack/MSFS2020-livery-manager#129]
## Description

FS2020 didn't start anymore

## To reproduce

1. Click this
2. Type that
3. Turn off your PC

## Environment

**Manager version:**

**FS2020 Version:**

## Screenshots or videos

<details>
<summary>Click to expand</summary>
Faulting application name: FlightSimulator.exe, version: 0.0.0.0, time stamp: 0x5f7c8cf2
Faulting module name: ucrtbase.dll, version: 10.0.19041.546, time stamp: 0x43cbc11d
Exception code: 0xc0000409
Fault offset: 0x0000000000071218
Faulting process id: 0x15c
Faulting application start time: 0x01d6aab7a4032baf
Faulting application path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.9.5.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: a698eb6c-ecad-4c04-a04f-15e99e699659
Faulting package full name: Microsoft.FlightSimulator_1.9.5.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

</details>

**Comment by davwheat** [comment]
Please complete the full bug report template.

There is currently a known issue with the Longitude liveries, so please uninstall those and wait for a patch to be rolled out.
