### ISSUE TITLE
[BUG] Manager blank after setup (FD error)

### ISSUE THREAD

**Issue by mmckernan599** [MSFS-Mega-Pack/MSFS2020-livery-manager#138]
## Description

Livery manager installs as expected, but when opening it, it briefly displays the header with window commands (close, minimize etc.), then it all disappears leaving a blank window with only the background pattern displayed and nothing else. See attached image.

1. Install Livery Manager
2. Open it

## Environment

The latest, can't check version number because I can't open the manager.
![Capture](https://user-images.githubusercontent.com/73439871/97114955-43f7b480-16b9-11eb-90de-c94f51d12f5f.JPG)

**Manager version:**

**FS2020 Version:**

## Screenshots or videos

<details>
<summary>Click to expand</summary>

</details>

**Comment by davwheat** [comment]
@mmckernan599 This is a known issue but we have no clue what causes it.

Did you use the browse dialog to find your community folder, or did you type it in.

You need to...

1. press Win + R
2. type `%appdata%`
3. Close the manager
4. Delete the folder called `Liveries Mega Pack Manager`
5. Restart the manager

**Comment by mmckernan599** [comment]
Ahhh, I think I got it. So I did that, and it goes through the setup process, it automatically finds my community folder, click next to get to the final setup page, click "finish" in the bottom right-hand corner, and after doing so the same "empty" manager window previously described pops up. I close the manager and open it using the desktop icon and I'm back it's the same empty window as before. So I tried that again and instead MANUALLY selected my community folder and it seems to be working now (despite the auto-fill for the folder looking correct earlier).

**Comment by davwheat** [comment]
The thing is that others have just let it detect their community folder and the manager had worked for them.

I'll try to look into this further. Thank you for helping us troubleshoot! :)

**Comment by mmckernan599** [comment]
No Problem! I appreciate the speedy response :)

**Comment by davwheat** [comment]
Ok, this issue seems to be to do with the auto-detection of the community folder...

I'll do some testing later.
