### ISSUE TITLE
Add livery manager

### ISSUE THREAD

**Issue by davwheat** [MSFS-Mega-Pack/MSFS2020-livery-manager#14]
Progress for the livery manager will be tracked here.

Ping me if you've completed a feature so I can mark it complete.

(PR branch quality)
[![DeepScan grade](https://deepscan.io/api/teams/10690/projects/13519/branches/230830/badge/grade.svg)](https://deepscan.io/dashboard#view=project&tid=10690&pid=13519&bid=230830)

@mentions represent who delivered/committed/worked on the feature

## Browse features

- [x] Show list of supported aircraft (@davwheat)
- [x] Show list of liveries for each aircraft (@davwheat)
- [x] See livery details (screenshot, name, description, author(s), etc) **SEMI-COMPLETE** (see note 1) (@davwheat)

## API features

- [x] Download all files from ~Google Drive~ BunnyCDN (@GewoonJaap)
- [x] Zip files (@GewoonJaap)
- [x] Reupload zips to ~GCP bucket~ BunnyCDN (@GewoonJaap)
- [x] Get zip URL and other metadata (@GewoonJaap)

## Installation features

- [x] Download livery from ~repo~ ~storage bucket@ BunnyCDN (@GewoonJaap)
- [x] Unzip livery (@GewoonJaap)
- [x] Install livery to community folder (@GewoonJaap)

## Management features

- [x] Fetch installed liveries (@GewoonJaap)
- [x] Prevent installation of already installed liveries (@davwheat)
  - [x] Display badge next to installed liveries (@davwheat)
  - [x] Disable checkboxes of installed liveries (@davwheat)
- [x] Uninstall liveries (#107) (@davwheat)
- [ ] Update liveries
  - [ ] View available updates
  - [ ] Per livery update button
  - [ ] Update all button

## General home page

- [x] Add update feed (@davwheat)
- [x] Add settings page (@davwheat)
- [x] Add update feed (@davwheat)

**Note 1:** There's no way to get a livery name or authors at the moment, so we can only display the version, a screenshot, and the file/folder name. :/

**Comment by JakeR04** [comment]
Hi, I am trying to use this app, but i cant seem to get it working. Could you please help me. I have downloaded the folder but have no idea on how to open it.

**Comment by davwheat** [comment]
@JakeR04 the app isn't ready for release yet -- we're still working on the final features.

You'll be able to get the app on the [Mega pack Discord](https://discord.gg/megapack), or from GitHub.
