### ISSUE TITLE
[FEAT] Please allow to resize window.

### ISSUE THREAD

**Issue by sldghmmr** [MSFS-Mega-Pack/MSFS2020-livery-manager#151]
## Description

Seeing the livery is essential to choosing to download it.  I wish there was more focus on its presentation. The window is already cramped due to complications with scrolling (I will also report this).

## Solution

Allow to expand/resize the window.

### Why is this the best solution?

Being able expand the window full size will allow more, clearer information to choose from.

## Additional context

I will also report the difficulties with expanding and collapsing liveries, possibly as a result of the crunched window.

**Comment by davwheat** [comment]
Browsing difficulties will be related, but the size of the lists are fixed due to the virtualised lists we use.

**Comment by sldghmmr** [comment]
Obviously.  But the window is so small that the expanded livery extends beyond the provided window.  You literally need to scroll to see all of the livery selected.
