### ISSUE TITLE
software loads then leaves blank screen

### ISSUE THREAD

**Issue by shorty321** [MSFS-Mega-Pack/MSFS2020-livery-manager#173]
Thanks, for a great program!
On loading for a second time loading screen is just a blank with no text with a scroll box.
Any ideas how to fix?
tried reinstall but
![Screenshot 2020-11-12 161220](https://user-images.githubusercontent.com/74337610/98890917-e7422980-2501-11eb-80f5-3f5e701ddf4e.png)
 to no avail.

**Comment by Roboplayer999** [comment]
I have the same issue

**Comment by davwheat** [comment]
Please read the known issues.

**Comment by Roboplayer999** [comment]
On Discord, i have

**Comment by davwheat** [comment]
It's literally pinned in the issues page here: #130
