### ISSUE TITLE
[BUG] READ ALL UPDATES button leads to empty page

### ISSUE THREAD

**Issue by tomihbk** [MSFS-Mega-Pack/MSFS2020-livery-manager#177]
## Description

At the home page of the program. When you scroll at the bottom of the window, there is a button named "READ ALL UPDATES". Once clicked, the manager just shows a blank page. You don't have the top window controls either.

## To reproduce

1. Open Megapack manager
2. At home page, scroll at the bottom of the window
3. Click on the button "READ ALL UPDATES"

## Environment

**Manager version: 0.3.0**

**FS2020 Version: 1.10.11.0**

## Screenshots or videos

https://youtu.be/RjzPKsBEMNc

**Comment by davwheat** [comment]
Thanks for the bug report!

We've fixed this issue on here, and we should push out an update around Christmas.
