### ISSUE TITLE
Liveries Mega Pack v0.3.1 error when installing

### ISSUE THREAD

**Issue by Wolfred19** [MSFS-Mega-Pack/MSFS2020-livery-manager#181]
Good day

Please could someone advise on the following error received when trying to install above mentioned for MSFS 2020.

Please see attached setup log which is popped up.
[SquirrelSetup.log](https://github.com/MSFS-Mega-Pack/MSFS2020-livery-manager/files/5552777/SquirrelSetup.log)

**Comment by GewoonJaap** [comment]
Could you try opening it as an administrator? (Right click the .exe -> Run as admin)

**Comment by Wolfred19** [comment]
Hi Jaap

Many thanks for response.

I eventually went into user/app data/and cleared out all folders pertaining to Livery Manager. There was more than one.

It then installed correctly.

Thanks again.

Regards
Wolfgang



Sent from my iPhone

On 17 Nov 2020, at 14:10, Jaap <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you try opening it as an administrator? (Right click the .exe -> Run as admin)
