### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mintytsar** [MSFS-Mega-Pack/MSFS2020-livery-manager#200]
## Description

UI is nothing but a scroll bar

## To reproduce

1. open livery manager
2. wait 1-3 seconds
3. bug

## Environment

**Manager version: 0.3.1**

**FS2020 Version: 1.11.6.0**

## Screenshots or videos

<details>
<summary>Click to expand</summary>

![Screenshot 2020-11-29 194856](https://user-images.githubusercontent.com/75231233/100561817-05839400-330e-11eb-875c-e12ed7717bc0.png)

</details>

**Comment by davwheat** [comment]
Please read the list of known issues.

**Comment by mintytsar** [comment]
Where are the known issues located?

**Comment by davwheat** [comment]
On the known issues page: #130
