### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Richard563** [MSFS-Mega-Pack/MSFS2020-livery-manager#221]
## To reproduce

1. Click this
2. Type that
3. Turn off your PC

## Environment

**Manager version:**

**FS2020 Version:**

## Screenshots or videos
best mega livery, fs approach pilot in demand ,it says its installed correctly ,however no new landing challengers ,downloaded from discord 
<details>
<summary>Click to expand</summary>

</details>

**Comment by davwheat** [comment]
This is for the mega pack manager only. For issues with the mega pack itself, please open a ticket on the Discord server.
