### ISSUE TITLE
Failing to install the Livery Manager.

### ISSUE THREAD

**Issue by modemair** [MSFS-Mega-Pack/MSFS2020-livery-manager#245]
## Description

Maybe not a bug, but the UI is missing on my screen. I only see a dark rectangle without the tabs on top.

## To reproduce

After running the installer, the program starts but the UI is missing. Closing the LiveryManager only possible using the Task Manager in Windows10 (Home 64bit).

1. Click this
2. Type that
3. Turn off your PC

## Environment

**Manager version:**
Version 0.4.0
**FS2020 Version:**
1.12.13.0
## Screenshots or videos
![image](https://user-images.githubusercontent.com/76730500/103277112-8cd52d80-49c8-11eb-8a9e-a6ac17f7116f.png)

<details>
<summary>Click to expand</summary>

</details>

**Comment by davwheat** [comment]
Hi @modemair 

This is a known issue, but there's a solution available in #130.

**Comment by modemair** [comment]
Fixed, thanks a lot!
