### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by alfie75** [MSFS-Mega-Pack/MSFS2020-livery-manager#266]
## To reproduce

1. Click this
2. Type that
3. Turn off your PC

## Environment

**Manager version:**

**FS2020 Version:**

## Screenshots or videos

<details>
<summary>Click to expand</summary>

</details>

**Comment by davwheat** [comment]
If you're having an issue, open a ticket on the Discord, or fill in the bug report template fully.
