### ISSUE TITLE
[I18N] I made a translation. How can I share it?

### ISSUE THREAD

**Issue by zephirus** [MSFS-Mega-Pack/MSFS2020-livery-manager#284]
## Description

I made a translation. How can I share it?
It's pt-PT (Portuguese)

**Comment by davwheat** [comment]
Instructions are under the locales folder. You need to push your changes to GitHub, assuming you edited and tested locally, then create a Pull Request.

**Comment by zephirus** [comment]
I can't push my changes.

I get this error:
Remote: Permission to MSFS-Mega-Pack/MSFS2020-livery-manager.git denied to zephirus. unable to access 'https://github.com/MSFS-Mega-Pack/MSFS2020-livery-manager.git/': The requested URL returned error: 403

**Comment by davwheat** [comment]
You need to create a fork of the repo.

Once you have, run

```
git remote set-url origin <URL to your forked repo>
```

Then you should be able to push and make a PR.

**Comment by zephirus** [comment]
Thanks! Got it, I think...
