### ISSUE TITLE
[FEAT] Linux Support

### ISSUE THREAD

**Issue by nordcomputer** [MSFS-Mega-Pack/MSFS2020-livery-manager#291]
## Description

I am playing this game via proton (Linux). Since I am not able to start the setup, it would be nice to have a Linux version.
I dont know in detail, how the program works, but I assume, it just copies the livery files into the community directory. I shouldnt be that hard to do that in Linux.

**Comment by davwheat** [comment]
This app is made for Windows and uses Windows-specific paths and feature to work.

I have no experience with app creation on Linux. You're welcome to fork the project to try to work it out, but I won't be able to. Sorry.

**Comment by nordcomputer** [comment]
No problem - its still a niche I think.
