### ISSUE TITLE
Livery doesn't show in-game[BUG] 

### ISSUE THREAD

**Issue by Pivot021** [MSFS-Mega-Pack/MSFS2020-livery-manager#351]
## Description

After choosing some liveries, they do not show in game.
For example, the 787 Dreamliner, neither of the Air Force One skins show, it's just a white plane.
## Environment

**Manager version:**
v0.4.5

**FS2020 Version:**
1.14. 5.0

<details>
<summary>Click to expand</summary>

![Dreamliner](https://user-images.githubusercontent.com/80713330/111204745-6d47ad00-8594-11eb-99f9-1646e5f43d52.PNG)

</details>

**Comment by GewoonJaap** [comment]
These liveries are old and no longer being supported by MSFS
