### ISSUE TITLE
[BUG] Livery CDN offline

### ISSUE THREAD

**Issue by thebg18** [MSFS-Mega-Pack/MSFS2020-livery-manager#506]
## Description
Hello a I have a issue my livries manager is stuck a downloading 1 of X and I restarte the pc the program and everything and still stuck 

## To reproduce

1. Click this
2. Type that
3. Turn off your PC

## Environment

**Manager version:**

**FS2020 Version:**

## Screenshots or videos

<details>
<summary>Click to expand</summary>

</details>

**Comment by davwheat** [comment]
The mega pack project is no longer active, and our downloads system has been shut down, hence your issue.

**Comment by davwheat** [comment]
Pretty much final.

**Comment by GewoonJaap** [comment]
At the moment, I am trying to get it back online, by moving all of our files to GitHub. I hope this will be ready today :)
(It looks like most of the files are still cached by Cloudflare so the manager is still working for some people, including me.)

**Comment by GewoonJaap** [comment]
The project is indeed stopped, we won't develop it anymore. We will try and fix some bugs if people create a pull request since we see that the manager is still being used.
