### ISSUE TITLE
[BUG] Problems with the liveries on the Boeing 787-10

### ISSUE THREAD

**Issue by siegmulo** [MSFS-Mega-Pack/MSFS2020-livery-manager#508]
## Description

Some liveries eg Qatar, Lufthansa, United Airlines, Singapore etc. show wings in pink colour. Please have a look in the textures.

## To reproduce

1. Click this
2. Type that
3. Turn off your PC

## Environment

**Manager version:**v0.5.2

**FS2020 Version:**1.20.6.0

## Screenshots or videos

<details>
<summary>Click to expand</summary>

</details

[Bug Liveries Boeing 787-10.pdf](https://github.com/MSFS-Mega-Pack/MSFS2020-livery-manager/files/7492102/Bug.Liveries.Boeing.787-10.pdf)
>

**Comment by davwheat** [comment]
This issue tracker is for issues with the manager itself, not liveries.
