### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by brendamdib** [MSFS-Mega-Pack/MSFS2020-livery-manager#527]
## Description

I installed successfully the Liveries Mega Pack Manager, but I have a problem to load the application.

## To reproduce

Just open the application

## Environment

**Manager version:**
0.5.3

**FS2020 Version:**
1.29.25.0
## Screenshots or videos
![image](https://user-images.githubusercontent.com/7771613/197402642-c4c532c7-13ad-4ba5-b7fa-39f1eefc1648.png)
![image](https://user-images.githubusercontent.com/7771613/197402655-2d15ead5-b221-4a83-bb5f-40eb4c37f94f.png)

What could I do, to solve this problem?

**Comment by GewoonJaap** [comment]
Sadly the manager is no longer operational. 
See: https://www.projectmegapack.com/ for our new site and a new way to download liveries
